### ISSUE TITLE
Feature for the Glide Hexa Ultra

### ISSUE THREAD

**Issue by LandoFerngully** [constructorfleet/homebridge-ultimate-govee#247]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

This was the output from the logs that ran:

"device":"43:8B:F0:EE:D7:97:AB:87","deviceName":"Glide Hexa Ultra","model":"H606A","httpInfo":{"groupId":14451919,"device":"43:8B:F0:EE:D7:97:AB:87","sku":"H606A","spec":"","versionHard":"3.04.01","versionSoft":"1.00.09","deviceName":"Glide Hexa Ultra","deviceExt":{"deviceSettings":"{\"wifiName\":\"PizzaPlanet\",\"address\":\"F0:EE:D7:97:AB:87\",\"bleName\":\"Govee_H606A_AB87\",\"topic\":\"GD/b1b48fcc0d52639bf86063e954c46b96\",\"wifiMac\":\"D4:AD:FC:EA:25:A8\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"\",\"wifiHardVersion\":\"\",\"ic\":330,\"secretCode\":\"Uy/w7teXq4c=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"dspVersionSoft\":12,\"shapes\":\"CgZABkAGAAAG8gVABgAABhkG/AUAAAZABrgFAAAGaAZzBQAABo8GuAUAAAZoBvwFAAAGtwb8BQAABo8GQAYAAAbeBkAGAAABAAAGAQIQCAEIAQgBIAQBCBACAQgQAgA=\",\"sku\":\"H606A\",\"device\":\"43:8B:F0:EE:D7:97:AB:87\",\"deviceName\":\"Glide Hexa Ultra\",\"versionHard\":\"3.04.01\",\"versionSoft\":\"1.00.09\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/5d84bf48453d3911792e756f3b7efd4b-add_list_type_device_606a.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":33}"},"pactType":1,"pactCode":1,"share":0,"goodsType":163,"attributesId":63,"supportScene":0}}

**Comment by Teagan42** [comment]
So, those panels are not like any of the devices I've decoded. Without access to the messages related to these panels, the best I can do is add it as a variable-length RGBIC light - if it behaves moderately acceptable then great - if not I'll have to pull it back out. If you try `v2.90.0` and find the behavior completely unacceptable, please reopen this issue. Otherwise I will assume that it works well-enough

 There are a LOT of GOVEE devices - I don't have the money or time to thoroughly investigate and decode them all
