### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by bwp91** [constructorfleet/homebridge-ultimate-govee#26]
Hey,

Haven’t tried your plugin yet, but, seems like you’ve put a lot of work into it!

Point is, I own the homebridge-govee plugin, I wouldn’t want to get to the point, like other plugins have done, where there is a choice between one plugin doing better in some way and another in other ways.

So wondered if you’d like to work together to create one big awesome govee plugin!

It seems like you’re really knowledgeable in some of the govee protocol where perhaps i am not.

Ben

**Comment by Teagan42** [comment]
Hey Ben,

I think we can do something together! I am refactoring the Modes state to work with loading accessories from cache, they are losing state attributes due to class inheritance (this is the first Homebridge plugin I have made and had to learn Typescript to do). I spent a lot of time decoding and deciphering the hex operation codes, you can see a write up here https://blog.teagantotally.rocks/2022/02/12/the-ultimate-govee-homebridge-plugin/

Email that@teagantotally.rocks and we’ll set up some further discussion.

**Comment by Teagan42** [comment]
Offline discussion
